server:
  port: ${PORT:8080}

spring:
  application:
    name: smart-attendance-backend
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://aws.connect.psdb.cloud/smart-attendance?sslMode=REQUIRE&useSSL=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

# Application Specific Properties
smart:
  attendance:
    app:
      jwtSecret: ${JWT_SECRET:SmartAttendanceSecretKeyForJWTsThatIsVeryLongAndSecure12345}
      jwtExpirationMs: 86400000 # 24 hours

# Face Recognition Service URL
face-recognition:
  service:
    url: ${FACE_RECOGNITION_URL:http://localhost:5000}

# Attendance Configuration
attendance:
  periods:
    - number: 1
      start: "09:30"
      end: "10:20"
    - number: 2
      start: "10:20"
      end: "11:10"

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://6864bc010b4af4783a60daa4--smart-attendance-ai.netlify.app,https://smart-attendance-ai.netlify.app}

# Logging
logging:
  level:
    com.smartattendance: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
