server:
  port: ${PORT:8080}

spring:
  application:
    name: smart-attendance-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/smart_attendance?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Application Specific Properties
smart:
  attendance:
    app:
      jwtSecret: ${JWT_SECRET:SmartAttendanceSecretKeyForJWTsThatIsVeryLongAndSecure12345}
      jwtExpirationMs: 86400000 # 24 hours

# Face Recognition Service URL
face-recognition:
  service:
    url: ${FACE_RECOGNITION_URL:http://localhost:5000}

# Attendance Configuration
attendance:
  periods:
    - number: 1
      start: "09:30"
      end: "10:20"
    - number: 2
      start: "10:20"
      end: "11:10"

# Logging
logging:
  level:
    com.smartattendance: ${LOG_LEVEL:DEBUG}
    org.springframework.security: DEBUG

